### ISSUE TITLE
Random IPv6

### ISSUE THREAD

**Issue by nik736** [ipaddress-gem/ipaddress#100]
Thanks for this gem. I have an IPv6 /64 where I want to get a random IP from, what's the most efficient way to do this?

**Comment by msimkins** [comment]
You can just generate a random 64 bits and then convert to hex then append to your /64 IP block. 

I am not totally sure I see a use case in the gem.

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old and haven't gotten much attention, I'll close it down.

Feel free to open up a discussion under the 'Discussions' tab if you think this is a missing feature, and would like to gauge other peoples interest in the functionality.

By closing some old issues we reduce the list of open issues to a more manageable set. I hope you understand!
