### ISSUE TITLE
release a new version of the gem???

### ISSUE THREAD

**Issue by spovich** [ipaddress-gem/ipaddress#117]
The last release was 4 years ago.  The project seems to be actively maintained, so just wondering if there is a reason for no release?

**Comment by Adam21e** [comment]
@spovich I did fork the gem and apply all the pull requests here:
https://github.com/ipaddress2-gem/ipaddress_2

Released it as a gem: ipaddress_2

**Comment by spovich** [comment]
@Adam21e great, thank you!  Giving it a look now.

**Comment by Ri1a** [comment]
It would be great if a new version of this gem can be released... it's unusable at this point because of Issues like https://github.com/ipaddress-gem/ipaddress/issues/107 or https://github.com/ipaddress-gem/ipaddress/issues/110 where you must tweak stuff to get this gem properly working. Frustrating!

**Comment by sandstrom** [comment]
Tracking this here: https://github.com/ipaddress-gem/ipaddress/issues/132

Closing this issue, as I'm going through and cleaning up some outstanding issues.
