### ISSUE TITLE
ipv4 abbreviation not supported

### ISSUE THREAD

**Issue by ghost** [ipaddress-gem/ipaddress#20]
> IPAddress::valid_ipv4? '10.1'
> => false 

$ ping 10.1
PING 10.1 (10.0.0.1): 56 data bytes

to be honest, not that critical, but still for completenes...

**Comment by mikerodrigues** [comment]
I'm interested in implementing this, it seems to be a rather interesting topic: http://superuser.com/questions/486788/why-does-pinging-192-168-072-only-2-dots-return-a-response-from-192-168-0-58

[17] pry(main)> IPAddress.parse("192.168.072").to_s
ArgumentError: Invalid IP "192.168.072"

Should return "192.168.0.58"

[2] pry(main)> IPAddress.parse("192.168.0.072").to_s
=> "192.168.0.072"

Should also return "192.168.0.58"

At least that's how they're interpreted when testing with `ping` on linux.

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old and haven't gotten much attention, I'll close it down.

Feel free to open up a discussion under the 'Discussions' tab if you think this is a missing feature, and would like to gauge other peoples interest in the functionality.

By closing some old issues we reduce the list of open issues to a more manageable set. I hope you understand!
