### ISSUE TITLE
Extra files in the gem

### ISSUE THREAD

**Issue by jcourteau** [ipaddress-gem/ipaddress#23]
Hello:

I'm packaging this up as an RPM for Fedora (and in the future, EPEL) as a dependency for Chef, and during the packaging process I noticed that the gem has several unneeded files in it, namely .document and (arguably) the gemspec.  I'm manually excluding them in the RPM but I thought I'd bring it to your attention for your next release.

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old and haven't gotten much attention, I'll close it down.

Feel free to open up a discussion under the 'Discussions' tab if you think this is a missing feature, and would like to gauge other peoples interest in the functionality.

By closing some old issues we reduce the list of open issues to a more manageable set. I hope you understand!

***

Regarding the extra files, I'll clean them up before the next release.
